config/routes.rb
Rails.application.routes.draw do
  get "problems/index"
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  ActiveAdmin.routes(self)

  resources :users, only: [] do
    resource :settings, only: [:show, :update]
  end

  root to: "home#index"

  resources :uploads, only: [:index, :create]
  resources :libraries do
    member do
      post "scan"
    end
    collection do
      post "scan", action: :scan_all
    end
    resources :models, except: [:index] do
      member do
        post "merge"
      end
      resources :model_files, except: [:index] do
        collection do
          get "edit", action: "bulk_edit"
          patch "update", action: "bulk_update"
        end
      end
    end
  end
  resources :models, only: [:index] do
    collection do
      get "edit", action: "bulk_edit"
      patch "/update", action: "bulk_update"
    end
  end
  resources :creators
  resources :collections
  resources :problems, only: [:index, :update]
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :models, dependent: :nullify
  has_many :collections, dependent: :nullify
  has_many :links, as: :linkable, dependent: :destroy
  belongs_to :collection, optional: true
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  validates :name, uniqueness: {case_sensitive: false}
  validates :slug, uniqueness: true

  before_validation :slugify_name, if: :name_changed?

  default_scope { order(:name) }
  # returns all collections at and below given ids
  #   this should be applied to @filters[:collection] to get models in sub-trees
  scope :tree_down, ->(id) {
    id ?
    where("collections.id IN (With RECURSIVE search_tree(id) AS (
      select id from collections where id IN (#{[*id].join(",")})
      union all
      select collections.id from search_tree join collections on collections.collection_id = search_tree.id where NOT collections.id IN (search_tree.id)
    ) select id from search_tree)") : where(collection_id: nil)
  }

  # returns root top-level collections for given ids
  scope :tree_up, ->(id) {
    id ?
    where("collections.id IN (WITH RECURSIVE search_tree(id, path) AS (
      SELECT id, id
      FROM collections
      WHERE collection_id is NULL
    UNION ALL
      SELECT collections.id, path           FROM search_tree
      JOIN collections ON collections.collection_id = search_tree.id
      WHERE NOT collections.id IN (path)
    ) select id from search_tree where id IN (?))", id) : where(collection_id: nil)
  }

  # returns root top-level collections for given collection ids, limited by the top-level ids
  #    top:  @filter[:collection]
  #    id:  collections from models resulting from searches
  scope :tree_both, ->(top, id) {
    top ?
    where("collections.id IN (WITH RECURSIVE search_tree(id, path) AS (
      SELECT id, id
      FROM collections
      WHERE collection_id IN (#{[*top].join(",")})
    UNION ALL
      SELECT collections.id, path           FROM search_tree
      JOIN collections ON collections.collection_id = search_tree.id
      WHERE NOT collections.id IN (path)
    ) select id from search_tree where id IN (?))", id) : tree_up(id)
  }

  #  Basic query that returns list of all collections with their path as csv
  #     WITH RECURSIVE search_tree(id, path) AS (
  #         SELECT id, id
  #         FROM collections
  #         WHERE collection_id is NULL
  #       UNION ALL
  #         SELECT collections.id, path || ',' || collections.id
  #         FROM search_tree
  #         JOIN collections ON collections.collection_id = search_tree.id
  #         WHERE NOT collections.id IN (path)
  #     )  SELECT * FROM search_tree

  def self.ransackable_attributes(_auth_object = nil)
    ["caption", "created_at", "id", "name", "notes", "slug", "updated_at"]
  end

  def self.ransackable_associations(_auth_object = nil)
    ["collection", "collections", "links", "models"]
  end

  private

  def slugify_name
    self.slug = name.parameterize
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  include ModelFilters
  before_action :get_collection, except: [:index, :new, :create]

  def index
    if @filters.empty?
      @collections = Collection.all
      @commontags = @tags = ActsAsTaggableOn::Tag.all
    else
      process_filters_init
      process_filters_tags_fetchall
      process_filters
      process_filters_tags_highlight
      @collections = Collection.tree_both(@filters[:collection] || nil, @models.filter_map { |model| model.collection_id })
    end

    # Ordering
    @collections = case session["order"]
    when "recent"
      @collections.order(created_at: :desc)
    else
      @collections.order(name: :asc)
    end

    if current_user.pagination_settings["collections"]
      page = params[:page] || 1
      @collections = @collections.page(page).per(current_user.pagination_settings["per_page"])
    end
    render layout: "card_list_page"
  end

  def show
    redirect_to models_path(collection: params[:id])
  end

  def new
    @collection = Collection.new
    @collection.links.build if @collection.links.empty? # populate empty link
    @title = t("collections.general.new")
    @collections = Collection.all
  end

  def edit
    @collection.links.build if @collection.links.empty? # populate empty link
    @collections = Collection.all
  end

  def create
    @collection = Collection.create(collection_params)
    redirect_to collections_path, notice: t(".success")
  end

  def update
    @collection.update(collection_params)
    redirect_to collections_path, notice: t(".success")
  end

  def destroy
    @collection.destroy
    redirect_to collections_path, notice: t(".success")
  end

  private

  def get_collection
    if params[:id] == "0"
      @collection = nil
      @title = t(".unknown")
    else
      @collection = Collection.find(params[:id])
      @title = @collection.name
    end
  end

  def collection_params
    params.require(:collection).permit([
      :name,
      :collection_id,
      :caption,
      :notes,
      links_attributes: [:id, :url, :_destroy]
    ])
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<% model = collection.models.first %>
<div class="col mb-4">
  <div class="card preview-card">

    <% if model && (file = model.preview_file) %>
      <% if file.is_image? %>
        <%= content_tag :div, nil, class: "card-img-top card-img-top-background", style: "background-image: url(#{library_model_model_file_path(model.library, model, file, format: file.extension)})" %>
        <%= image_tag library_model_model_file_path(model.library, model, file, format: file.extension), class: "card-img-top image-preview ", alt: file.name %>
      <% elsif renderable?(file.extension) %>
        <div class="card-img-top">
          <%= render partial: "object_preview", locals: {library: model.library, model: model, file: file} %>
        </div>
      <% end %>
       <% else %>
       <div class='preview-empty'> <p><%= t ".no_preview" %></p></div>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= collection.name.titleize %></h5>
      <div class="col-auto">
        <% if collection.collection %>
          <%= icon "collection", t("activerecord.models.collection") %>
          <%= link_to collection.collection.name, (@filters || {}).merge(collection: collection.collection.id) %><br>
        <% end %>
        <% if collection.caption %>
          <h6 class="card-subtitle mb-2 text-muted"><%= sanitize collection.caption %></h6>
        <% end %>
        <% if collection.notes && collection.notes != "" %>
          <p class="card-text"><%= sanitize collection.notes %></p>
        <% end %>
        <ul class='links'>
          <% collection.links.each do |link| %>
            <li><%= link_to t("sites.%{site}" % {site: link.site}), link.url %></li>
          <% end %>
        </ul>
      </div>
      <div>
        <%= link_to pluralize(collection.models.count, t("activerecord.models.model")), {controller: "models", collection: collection.id}, class: "btn btn-primary" %>
        <%= link_to(pluralize(collection.collections.count, t("activerecord.models.collection")), (@filters || {}).merge(controller: "collections", collection: collection.id), class: "btn btn-primary") if collection.collections.count > 0 %>
        <%= link_to t("general.edit"), edit_collection_path(collection), {class: "btn btn-outline-secondary"} %>
      </div>
    </div>
  </div>
</div>

app/views/collections/_form.html.erb
<%= form_with model: @collection do |form| %>
  <%= text_input_row form, :name %>
  <div class="row mb-3 input-group">
    <%= form.label :collection_id, class: "col-sm-2 col-form-label" %>
    <%= form.collection_select :collection_id, @collections, :id, :name, {include_blank: true}, {class: "form-control col-auto form-select"} %>
    <%= link_to t("collections.general.new"), new_collection_path, class: "btn btn-outline-secondary col-auto" %>
  </div>
  <%= render "links_form", form: form %>
  <%= text_input_row form, :caption %>
  <%= rich_text_input_row form, :notes %>
  <div class="row mb-4">
    <div class='col'>
      <%= form.submit t("general.save"), class: "btn btn-primary" %>
    </div>
    <% if @collection.persisted? %>
      <div class='col text-end'>
        <%= link_to t("general.delete"), collection_path(@collection), {method: :delete, class: "btn btn-outline-danger"} %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1><%= t "collections.general.edit" %></h1>

<%= render "form" %>

app/views/collections/index.html.erb
<% content_for :page_header do %>
  <%= render "application/content_header" %>
<% end %>

<% content_for :items do %>
  <% if current_user.pagination_settings["collections"] %>
    <%= paginate @collections %>
  <% end %>
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 mb-4">
    <% if @filters[:collection] && @collection %>
      <%= render @collection %>
    <% end %>
    <%= render @collections %>
  </div>
  <% if current_user.pagination_settings["collections"] %>
    <%= paginate @collections %>
  <% end %>
<% end %>

<% content_for :sidebar do %>
  <%= card :secondary, t(".actions_heading") do %>
    <%= link_to t(".view_unassigned_models"), models_path(collection: ""), class: "btn btn-outline-secondary mb-3 me-3" %>
    <%= link_to t("collections.general.new"), new_collection_path, class: "btn btn-primary mb-3 me-3" %>
  <% end %>
  <%= render "filters_card" %>
  <% unless @tags.empty? %>
    <%= card :secondary, ActsAsTaggableOn::Tag.model_name.human.pluralize, collapse: "md" do %>
      <%= render "tag_list", tags: @tags - (@tag || []), muted_tags: @tags - @commontags %>
    <% end %>
  <% end %>
<% end %>

app/views/collections/new.html.erb
<h1><%= t("collections.general.new") %></h1>

<%= render "form" %>

app/views/collections/show.html.erb
<div class="row row-cols-2">
  <div class="col-9">
    <div class="row row-cols-2 align-items-baseline">
      <div class="col col-auto me-auto">
        <h1><%= @collection.name.titleize %></h1>
      </div>
      <div class="col col-auto ">
        <a href="?order=name" class="btn <%= (session["order"] == "name") ? "btn-secondary" : "btn-outline-secondary" %> btn-sm" title="sort by name"><i class="bi bi-book"></i></a>
        <a href="?order=recent" class="btn <%= (session["order"] == "recent") ? "btn-secondary" : "btn-outline-secondary" %> btn-sm" title="sort by time"><i class="bi bi-clock"></i></a>
      </div>
    </div>
  </div>
</div>
<div class="row row-cols-2">
  <div class="col-9">
    <% if current_user.pagination_settings["models"] %>
      <%= paginate @models %>
    <% end %>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 mb-4">
      <%= render partial: "model", collection: @models %>
    </div>
    <% if current_user.pagination_settings["models"] %>
      <%= paginate @models %>
    <% end %>
  </div>
  <div class="col-3">
  </div>
</div>