config/routes.rb
Rails.application.routes.draw do
  get "problems/index"
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  ActiveAdmin.routes(self)

  resources :users, only: [] do
    resource :settings, only: [:show, :update]
  end

  root to: "home#index"

  resources :uploads, only: [:index, :create]
  resources :libraries do
    member do
      post "scan"
    end
    collection do
      post "scan", action: :scan_all
    end
    resources :models, except: [:index] do
      member do
        post "merge"
      end
      resources :model_files, except: [:index] do
        collection do
          get "edit", action: "bulk_edit"
          patch "update", action: "bulk_update"
        end
      end
    end
  end
  resources :models, only: [:index] do
    collection do
      get "edit", action: "bulk_edit"
      patch "/update", action: "bulk_update"
    end
  end
  resources :creators
  resources :collections
  resources :problems, only: [:index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :models, dependent: :nullify
  has_many :collections, dependent: :nullify
  has_many :links, as: :linkable, dependent: :destroy
  belongs_to :collection, optional: true
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  validates :name, uniqueness: {case_sensitive: false}
  validates :slug, uniqueness: true

  before_validation :slugify_name, if: :name_changed?

  default_scope { order(:name) }
  # returns all collections at and below given ids
  #   this should be applied to @filters[:collection] to get models in sub-trees
  scope :tree_down, ->(id) {
    id ?
    where("collections.id IN (With RECURSIVE search_tree(id) AS (
      select id from collections where id IN (#{[*id].join(",")})
      union all
      select collections.id from search_tree join collections on collections.collection_id = search_tree.id where NOT collections.id IN (search_tree.id)
    ) select id from search_tree)") : where(collection_id: nil)
  }

  # returns root top-level collections for given ids
  scope :tree_up, ->(id) {
    id ?
    where("collections.id IN (WITH RECURSIVE search_tree(id, path) AS (
      SELECT id, id
      FROM collections
      WHERE collection_id is NULL
    UNION ALL
      SELECT collections.id, path           FROM search_tree
      JOIN collections ON collections.collection_id = search_tree.id
      WHERE NOT collections.id IN (path)
    ) select id from search_tree where id IN (?))", id) : where(collection_id: nil)
  }

  # returns root top-level collections for given collection ids, limited by the top-level ids
  #    top:  @filter[:collection]
  #    id:  collections from models resulting from searches
  scope :tree_both, ->(top, id) {
    top ?
    where("collections.id IN (WITH RECURSIVE search_tree(id, path) AS (
      SELECT id, id
      FROM collections
      WHERE collection_id IN (#{[*top].join(",")})
    UNION ALL
      SELECT collections.id, path           FROM search_tree
      JOIN collections ON collections.collection_id = search_tree.id
      WHERE NOT collections.id IN (path)
    ) select id from search_tree where id IN (?))", id) : tree_up(id)
  }

  #  Basic query that returns list of all collections with their path as csv
  #     WITH RECURSIVE search_tree(id, path) AS (
  #         SELECT id, id
  #         FROM collections
  #         WHERE collection_id is NULL
  #       UNION ALL
  #         SELECT collections.id, path || ',' || collections.id
  #         FROM search_tree
  #         JOIN collections ON collections.collection_id = search_tree.id
  #         WHERE NOT collections.id IN (path)
  #     )  SELECT * FROM search_tree

  def self.ransackable_attributes(_auth_object = nil)
    ["caption", "created_at", "id", "name", "notes", "slug", "updated_at"]
  end

  def self.ransackable_associations(_auth_object = nil)
    ["collection", "collections", "links", "models"]
  end

  private

  def slugify_name
    self.slug = name.parameterize
  end
end

app/models/concerns/path_builder.rb
module PathBuilder
  extend ActiveSupport::Concern

  def formatted_path
    SiteSettings.model_path_template.gsub(/{.+?}/) do |token|
      case token
      when "{tags}"
        (tags.count > 0) ?
          File.join(tags.order(taggings_count: :desc).map { |x| x.to_s.parameterize }) :
          "@untagged"
      when "{creator}"
        path_component(creator) || "@unattributed"
      when "{collection}"
        path_component(collection) || "@uncollected"
      when "{modelName}"
        path_component(self)
      when "{modelId}"
        "##{id}"
      else
        token
      end
    end
  end

  private

  def path_component(object)
    return nil if object.nil?
    SiteSettings.safe_folder_names ? object.slug : object.name
  end
end

app/models/concerns/path_parser.rb
module PathParser
  extend ActiveSupport::Concern

  def generate_tags_from_directory_name!
    tags = File.split(path).last.split(/[\W_+-]/).filter { |x| x.length > 1 }
    tag_list.add(remove_stop_words(tags))
  end

  def parse_metadata_from_path!
    return unless SiteSettings.model_path_template
    components = extract_path_components
    parse_tags(components[:tags])
    parse_creator(components[:creator])
    parse_collection(components[:collection])
    parse_name(components[:model_name])
    save!
  end

  private

  def parse_creator(component)
    return unless component
    self.creator = find_or_create_from_path_component(Creator, component)
  end

  def parse_collection(component)
    return unless component
    self.collection = find_or_create_from_path_component(Collection, component)
  end

  def parse_name(component)
    return unless component
    self.name = to_human_name(component)
  end

  def parse_tags(component)
    return unless component
    tag_list.add(remove_stop_words(component).map { |tag| tag.titleize.downcase })
  end

  def path_parse_pattern
    Regexp.new("^/?.*?" +
      SiteSettings.model_path_template.gsub(/{.+?}/) { |token|
        case token
        when "{tags}"
          "(?<tags>[[:print:]]*)"
        when "{creator}"
          "(?<creator>[[:print:]&&[^/]]*?)"
        when "{collection}"
          "(?<collection>[[:print:]&&[^/]]*?)"
        when "{modelName}"
          "(?<model_name>[[:print:]&&[^/]]*?)"
        when "{modelId}"
          "(?<model_id>#[[:digit:]]+)?"
        else
          "[[:print:]&&[^/]]*"
        end
      } + "$")
  end

  def extract_path_components
    components = path.match(path_parse_pattern)&.named_captures&.symbolize_keys
    return {} if components.nil?
    components.merge({
      tags: components[:tags]&.split("/")&.compact_blank,
      model_id: nil # discard ID, never gonna use it in parsing
    }).compact
  end

  def remove_stop_words(words)
    return words if !SiteSettings.model_tags_filter_stop_words
    stopword_filter = Stopwords::Snowball::Filter.new(
      SiteSettings.model_tags_stop_words_locale,
      SiteSettings.model_tags_custom_stop_words
    )
    stopword_filter.filter(words)
  end

  def find_or_create_from_path_component(klass, path_component)
    klass.find_by(slug: path_component) ||
      klass.create_with(slug: path_component.parameterize).find_or_create_by(
        name: to_human_name(path_component)
      )
  end

  def to_human_name(str)
    str.humanize.tr("+", " ").titleize
  end
end

app/models/creator.rb
class Creator < ApplicationRecord
  has_many :models, dependent: :nullify
  has_many :links, as: :linkable, dependent: :destroy
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  validates :name, uniqueness: {case_sensitive: false}
  validates :slug, uniqueness: true

  default_scope { order(:name) }

  before_validation :slugify_name, if: :name_changed?

  def self.ransackable_attributes(_auth_object = nil)
    ["caption", "created_at", "id", "name", "notes", "slug", "updated_at"]
  end

  def self.ransackable_associations(_auth_object = nil)
    ["links", "models"]
  end

  private

  def slugify_name
    self.slug = name.parameterize
  end
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["blocked", "created_at", "favoritable_id", "favoritable_type", "favoritor_id", "favoritor_type", "id", "scope", "updated_at"]
  end
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :models, dependent: :destroy
  has_many :model_files, through: :models
  has_many :problems, as: :problematic, dependent: :destroy
  serialize :tag_regex, Array
  after_initialize :init

  validates :path, presence: true, uniqueness: true, existing_path: true

  default_scope { order(:path) }

  def name
    self[:name] || (path ? File.basename(path) : "")
  end

  def init
    self.name = nil if name == ""
  end

  def all_tags
    models.includes(:tags).map(&:tags).flatten.uniq.sort_by(&:name)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["caption", "created_at", "icon", "id", "name", "notes", "path", "tag_regex", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["model_files", "models", "problems"]
  end
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  def host
    URI.parse(url).host
  end

  def site
    PublicSuffix.parse(host).sld.to_sym
  end

  def self.ransackable_attributes(_auth_object = nil)
    ["created_at", "id", "linkable_id", "linkable_type", "updated_at", "url"]
  end
end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :problematic, polymorphic: true

  validates :category, uniqueness: {scope: :problematic}, presence: true

  default_scope { where(ignored: false) }

  scope :visible, ->(settings) {
    enabled = settings.select { |cat, sev| sev.to_sym != :silent }
    where(category: enabled.keys)
  }

  CATEGORIES = [
    :missing,
    :empty,
    :destination_exists, # No longer used, but kept for compatibility
    :nesting,
    :inefficient,
    :duplicate,
    :no_image,
    :no_3d_model
  ]
  enum :category, CATEGORIES

  SEVERITIES = [
    :silent,
    :info,
    :warning,
    :danger
  ]

  DEFAULT_SEVERITIES = {
    missing: :danger,
    empty: :info,
    nesting: :warning,
    inefficient: :info,
    duplicate: :warning,
    no_image: :silent,
    no_3d_model: :silent
  }

  def self.create_or_clear(problematic, cat, present, options = {})
    if present
      problematic.problems.create(options.merge(category: cat))
    else
      problematic.problems.where(category: cat).destroy_all
    end
    present
  end

  def self.ransackable_attributes(auth_object = nil)
    ["category", "created_at", "id", "note", "problematic_id", "problematic_type", "updated_at"]
  end
end

app/models/site_settings.rb
# RailsSettings Model
class SiteSettings < RailsSettings::Base
  cache_prefix { "v1" }

  field :model_tags_filter_stop_words, type: :boolean, default: true
  field :model_tags_tag_model_directory_name, type: :boolean, default: false
  field :model_tags_stop_words_locale, type: :string, default: "en"
  field :model_tags_custom_stop_words, type: :array, default: (SupportedMimeTypes.image_extensions + SupportedMimeTypes.model_extensions)
  field :model_tags_auto_tag_new, type: :string, default: "!new"
  field :model_path_template, type: :string, default: "{tags}/{modelName}{modelId}"
  field :parse_metadata_from_path, type: :boolean, default: true
  field :safe_folder_names, type: :boolean, default: true
end

app/models/user.rb
class User < ApplicationRecord
  begin
    if Flipper.enabled? :multiuser
      devise :database_authenticatable, :registerable, :validatable
    else
      devise :database_authenticatable
    end
  rescue ActiveRecord::StatementInvalid
    # If we've not migrated Flipper yet, we'll get an exception, which we can swallow
  end

  acts_as_favoritor

  validates :username,
    presence: true,
    uniqueness: {case_sensitive: false},
    format: {with: /\A[[:alnum:]]{3,}\z/}

  def to_param
    username
  end

  def printed?(file)
    favorited?(file, scope: :printed)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "id", "updated_at", "username"]
  end
end

app/controllers/models_controller.rb
require "fileutils"

class ModelsController < ApplicationController
  include ModelFilters
  before_action :get_library, except: [:index, :bulk_edit, :bulk_update]
  before_action :get_model, except: [:bulk_edit, :bulk_update, :index]

  def index
    process_filters_init

    # Ordering
    @models = case session["order"]
    when "recent"
      @models.order(created_at: :desc)
    else
      @models.order(name: :asc)
    end

    if current_user.pagination_settings["models"]
      page = params[:page] || 1
      @models = @models.page(page).per(current_user.pagination_settings["per_page"])
    end

    process_filters_tags_fetchall
    process_filters
    process_filters_tags_highlight

    render layout: "card_list_page"
  end

  def show
    files = @model.model_files
    if current_user.file_list_settings["hide_presupported_versions"]
      hidden_ids = files.select(:presupported_version_id).where.not(presupported_version_id: nil)
      files = files.where.not(id: hidden_ids)
    end
    @groups = helpers.group(files)
    render layout: "card_list_page"
  end

  def edit
    @creators = Creator.all
    @collections = Collection.all
    @model.links.build if @model.links.empty? # populate empty link
  end

  def update
    if @model.update(model_params)
      redirect_to [@model.library, @model], notice: t(".success")
    else
      edit # Load creators and collections
      flash.now[:alert] = t(".failure")
      render :edit
    end
  end

  def merge
    if params[:target] && (target = (@model.parents.find { |x| x.id == params[:target].to_i }))
      @model.merge_into! target
      Scan::CheckModelIntegrityJob.perform_later(target.id)
      redirect_to [@library, target], notice: t(".success")
    elsif params[:all] && @model.contains_other_models?
      @model.contained_models.each do |child|
        child.merge_into! @model
      end
      Scan::CheckModelIntegrityJob.perform_later(@model.id)
      redirect_to [@library, @model], notice: t(".success")
    else
      render status: :bad_request
    end
  end

  def bulk_edit
    @creators = Creator.all
    @collections = Collection.all
    @models = Model.all
    process_filters
  end

  def bulk_update
    hash = bulk_update_params
    hash[:library_id] = hash.delete(:new_library_id) if hash[:new_library_id]

    add_tags = Set.new(hash.delete(:add_tags))
    remove_tags = Set.new(hash.delete(:remove_tags))

    params[:models].each_pair do |id, selected|
      if selected == "1"
        model = Model.find(id)
        if model.update(hash)
          existing_tags = Set.new(model.tag_list)
          model.tag_list = existing_tags + add_tags - remove_tags
          model.save
        end
      end
    end
    redirect_back_or_to edit_models_path(@filters), notice: t(".success")
  end

  def destroy
    authorize @model
    @model.delete_from_disk_and_destroy
    if URI.parse(request.referer).path == library_model_path(@library, @model)
      # If we're coming from the model page itself, we can't go back there
      redirect_to library_path(@library), notice: t(".success")
    else
      redirect_back_or_to library_path(@library), notice: t(".success")
    end
  end

  private

  def bulk_update_params
    params.permit(
      :creator_id,
      :collection_id,
      :new_library_id,
      :organize,
      :license,
      add_tags: [],
      remove_tags: []
    ).compact_blank
  end

  def model_params
    params.require(:model).permit(
      :preview_file_id,
      :creator_id,
      :library_id,
      :name,
      :caption,
      :notes,
      :license,
      :collection_id,
      :q,
      :library,
      :creator,
      :tag,
      :organize,
      :missingtag,
      tag_list: [],
      links_attributes: [:id, :url, :_destroy]
    )
  end

  def get_library
    @library = Model.find(params[:id]).library
  end

  def get_model
    @model = Model.includes(:model_files, :creator).find(params[:id])
    @title = @model.name
  end
end

app/helpers/models_helper.rb
module ModelsHelper
  def group(files)
    groups = files.group_by { |i| i.filename.split(/[\ _\-:.]/)[0] }
    ungrouped = []
    groups.each_pair do |group, p|
      ungrouped << groups.delete(group)[0] if p.count == 1
    end
    groups.merge(nil => ungrouped)
  end

  def status_badges(model)
    badges = []
    badges << content_tag(:span, icon("bi bi-stars", t("general.new")), class: "text-warning align-middle") if model.new?
    badges << problem_icon(model.problems_including_files.visible(current_user.problem_settings))
    content_tag :span, safe_join(badges, " "), class: "status-badges"
  end

  def license_select_options(selected: nil)
    # Generate a list of select options for select with a set of useful licenses
    options_for_select(
      %w[
        CC-BY-4.0
        CC-BY-NC-4.0
        CC-BY-ND-4.0
        CC-BY-NC-ND-4.0
        CC-BY-NC-SA-4.0
        CC-BY-SA-4.0
        CC-PDDC
        CC0-1.0
        MIT
        LicenseRef-Commercial
      ].map { |id|
        [
          t_license(id),
          id
        ]
      },
      selected: selected
    )
  end

  def t_license(license)
    t("licenses.%{id}" % {id: license.delete(".")}, default: license)
  end
end

app/views/models/_problem.html.erb
<%= card(problem_severity(problem), t("problems.model.%{cat}.title" % {cat: problem.category})) do %>
  <%= t(("problems.model.%{cat}.description" % {cat: problem.category}), note: problem.note) %>

  <% if @model.contains_other_models? %>
    <ul>
      <% @model.contained_models.each do |target| %>
        <li><%= link_to target.name, library_model_path(@library, target) %></li>
      <% end %>
    </ul>
    <p>
      <%= t("problems.model.nesting.warning") %>
    </p>
    <%= link_to t(".merge_all"), merge_library_model_path(@library, @model, all: true), class: "btn btn-danger", method: :post %>
  <% end %>

<% end %>

app/views/models/_tags_edit.html.erb
<div class="row mb-3 input-group">
  <%= form.label label, class: "col-sm-2 col-form-label" %>
  <div class="form-control col-auto tag-container">
    <%= form.collection_select :tag_list, tags,
          :name, :name, {}, {
            multiple: true,
            class: "form-select",
            name: name ? "#{name}[]" : nil,
            data: {selectize: "true"}
          } %>
  </div>
</div>

app/views/models/bulk_edit.html.erb
<h1>Bulk Edit <%= Model.model_name.human.pluralize %></h1>

<%= form_with url: update_models_path, method: :patch do |form| %>

  <h3>Select models to change:</h3>

  <table class="table table-striped" data-bulk-edit>
    <tr>
      <th><input type="checkbox" aria-label="Select All" value="0" name="bulk-select-all"></th>
      <th>Name</th>
      <th>Collections</th>
      <th>Tags</th>
      <th>Creator</th>
      <th>Organize files</th>
    </tr>
    <% @models.each do |model| %>
      <tr>
        <td><%= form.check_box "models[#{model.id}]", {data: {bulk_item: model.id.to_s}} %></td>
        <td><%= link_to model.name, [model.library, model], title: model.path %></td>
        <td><%= link_to model.collection.name, model.collection if model.collection %></td>
        <td><%= render partial: "tag",
                  collection: (current_user.tag_cloud_settings["sorting"] == "alphabetical") ?
                    model.tags.sort_by(&:name) : model.tags.sort_by(&:name).reverse.sort_by(&:taggings_count).reverse,
                  locals: {state: :normal, model_id: model.id} %></td>
        <td><%= link_to model.creator.name, model.creator if model.creator %></td>
        <td><code><%= model.formatted_path if model.needs_organizing? %></code></td>
      </tr>
    <% end %>
  </table>

  <h3>Select changes to make:</h3>

  <div class="row mb-3">
    <%= form.label :creator_id, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <div class="input-group">
        <%= form.collection_select :creator_id, @creators, :id, :name, {include_blank: true}, {class: "form-control col-auto form-select"} %>
        <%= link_to "New Creator", new_creator_path, class: "btn btn-outline-secondary col-auto" %>
      </div>
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :new_library_id, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.collection_select :new_library_id, Library.all, :id, :name, {include_blank: true}, {class: "form-control col-auto form-select"} %>
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :license, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :license, license_select_options, {include_blank: true}, {class: "form-control col-auto form-select"} %>
    </div>
  </div>

  <%= render "tags_edit", form: form, name: :add_tags, value: "", label: t(".add_tags"), tags: @addtags || [] %>
  <%= render "tags_edit", form: form, name: :remove_tags, value: "", label: t(".remove_tags"), tags: @models.includes(:tags).map(&:tags).flatten.uniq.sort_by(&:name) %>

  <div class="row mb-3">
    <%= form.label :collection_id, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <div class="input-group">
        <%= form.collection_select :collection_id, @collections, :id, :name, {include_blank: true}, {class: "form-control col-auto form-select"} %>
        <%= link_to "New Collection", new_collection_path, class: "btn btn-outline-secondary col-auto" %>
      </div>
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label "Organize files", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <div class="form-switch">
        <%= form.check_box :organize, class: "form-check-input form-check-inline" %>
      </div>
    </div>
  </div>
  <% if @filters[:tag] %>
    <% @filters[:tag].each do |tag| %>
      <%= form.hidden_field :tag, multiple: true, value: tag %>
    <% end %>
  <% end %>
  <%= form.hidden_field :q, value: @filters[:q] if @filters[:q] %>
  <%= form.hidden_field :collection, value: @filters[:collection] if @filters[:collection] %>
  <%= form.hidden_field :library, value: @filters[:library] if @filters[:library] %>
  <%= form.hidden_field :creator, value: @filters[:creator] if @filters[:creator] %>
  <%= form.submit "Update Selected Models", class: "btn btn-primary" %>

<% end %>

app/views/models/edit.html.erb
<%= render partial: "model_files/breadcrumb" %>
<h1><%= t("models.general.edit") %></h1>

<%= render "form" %>

app/views/models/show.html.erb
<% content_for :page_header do %>
  <h1>
    <a data-field="model[name]" data-path="<%= library_model_path(@model.library, @model) %>" contenteditable=true>
      <%= @model.name %>
    </a>
    <%= link_to icon("search", t(".search")),
          "https://yeggi.com/q/#{ERB::Util.url_encode(@model.name)}/",
          class: "btn btn-outline", target: "manyfold_search" %>
  </h1>
<% end %>

<% content_for :items do %>
  <h2><a name="files"><%= t(".files") %></a></h2>
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 mb-4">
    <%= render partial: "file", collection: @groups.delete(nil) %>
  </div>
  <% @groups.each_pair do |group, files| %>
    <h3><a name="<%= group.parameterize %>"><%= group %></a></h3>
    <div class="row  row-cols-1 row-cols-md-2 row-cols-lg-3 mb-4">
      <%= render partial: "file", collection: files %>
    </div>
  <% end %>
<% end %>

<% content_for :sidebar do %>
  <%= card :secondary, t(".model_details") do %>
    <table class="table table-borderless table-sm">
      <% if @model.creator %>
        <tr>
          <td><%= icon "person", Creator.model_name.human %></td>
          <td><%= link_to @model.creator.name, models_path((@filters || {}).merge(creator: @model.creator)) %></td>
        </tr>
      <% end %>
      <% if @model.collection %>
        <tr>
          <td><%= icon "collection", Collection.model_name.human.pluralize %></td>
          <td><%= link_to @model.collection.name, models_path((@filters || {}).merge(collection: @model.collection.id)) %></td>
        </tr>
      <% end %>
      <% if @model.library %>
        <tr>
          <td><%= icon "boxes", Library.model_name.human %></td>
          <td><%= link_to @model.library.name, models_path((@filters || {}).merge(library: @model.library)) %></td>
        </tr>
      <% end %>
      <% if @model.license %>
        <tr>
          <td><%= icon "card-heading", t(".license") %></td>
          <td>
            <%= Spdx.licenses[@model.license]&.fetch("reference") ?
              link_to(t_license(@model.license), Spdx.licenses[@model.license]["reference"]) :
              t_license(@model.license) %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td><%= icon "folder", t(".path") %></td>
        <td>
          <code><%= @model.path %></code>
          <% unless @model.contains_other_models? %>
            <%= button_tag(t(".organize.button_text"), class: "btn btn-warning btn-sm float-end", "data-bs-toggle": "modal", "data-bs-target": "#confirm-move") if @model.needs_organizing? %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td><%= icon "tag", t(".tags") %></td>
        <td><%= render "tag_list", tags: @model.tags.sort_by(&:taggings_count) %></td>
      </tr>
    </table>
    <%= link_to safe_join([icon("pencil", t("general.edit")), t("general.edit")], " "), edit_library_model_path(@library, @model), class: "btn btn-primary" %>
    <%= link_to safe_join([icon("trash", t("general.delete")), t("general.delete")], " "), library_model_path(@library, @model), {method: :delete, class: "float-end btn btn-outline-danger", data: {confirm: t("models.destroy.confirm")}} %>
  <% end %>

  <% unless @model.parents.empty? %>
    <%= card :danger, t(".merge.heading") do %>
      <p>
        <%= t(".merge.warning") %>
      </p>
      <strong><%= t(".merge.with") %>:</strong>
      <% @model.parents.each do |target| %>
        <%= link_to target.name, merge_library_model_path(@library, @model, target: target.id), class: "btn btn-danger", method: :post %>
      <% end %>
    <% end %>
  <% end %>

  <%= render partial: "problem", collection: @model.problems.visible(current_user.problem_settings) %>

  <%= card(:secondary, t(".notes_heading")) do %>
    <p class="card-text"><%= sanitize @model.notes %></p>
  <% end if @model.notes %>

  <%= card :secondary, t(".files_card.heading") do %>
    <a href="#files">Top</a>
    <ul>
      <% @groups.each_pair do |group, files| %>
        <li><a href="#<%= group.parameterize %>"><%= group %></a></li>
      <% end %>
    </ul>
    <%= link_to t(".files_card.bulk_edit"), edit_library_model_model_files_path(@library, @model), class: "btn btn-secondary" %>
  <% end %>

  <%= render "links_card", links: @model.links %>

  <div class="modal fade" id="confirm-move" data-bs-backdrop='static' tabindex="-1" aria-labelledby="confirmMoveLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="confirmMoveLabel"><%= t(".organize.button_text") %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>
            <%= t(".organize.confirm.summary_html", from: @model.path, to: @model.formatted_path) %>
          </p>
          <p>
            <%= t(".organize.confirm.are_you_sure") %>
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><%= t(".organize.confirm.no") %></button>
          <%= button_to t(".organize.confirm.yes"), library_model_path(@library, @model, "model[organize]": true), method: :patch, class: "btn btn-warning" %>
        </div>
      </div>
    </div>
  </div>
<% end %>