config/routes.rb
Rails.application.routes.draw do
  get "problems/index"
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  ActiveAdmin.routes(self)

  resources :users, only: [] do
    resource :settings, only: [:show, :update]
  end

  root to: "home#index"

  resources :uploads, only: [:index, :create]
  resources :libraries do
    member do
      post "scan"
    end
    collection do
      post "scan", action: :scan_all
    end
    resources :models, except: [:index] do
      member do
        post "merge"
      end
      resources :model_files, except: [:index] do
        collection do
          get "edit", action: "bulk_edit"
          patch "update", action: "bulk_update"
        end
      end
    end
  end
  resources :models, only: [:index] do
    collection do
      get "edit", action: "bulk_edit"
      patch "/update", action: "bulk_update"
    end
  end
  resources :creators
  resources :collections
  resources :problems, only: [:index, :update]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ModelFilters
  before_action :check_for_first_use

  def index
    @recent = Model.recent.limit(20)
  end

  private

  def check_for_first_use
    redirect_to new_library_path if Library.count === 0
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row bg-body-tertiary pt-3 mb-3 text-center">
  <%= render "application/content_header" %>
  <h1 class="d-none d-lg-block"><%= t "application.title" %></h1>
  <p class='lead'><%= t "application.tagline" %></p>
  <% if Flipper.enabled? :demo_mode %>
    <div class="alert alert-info">
      <%= t "application.demo_mode" %>
    </div>
  <% end %>
  <div class="col-8 offset-md-2">
    <%= form_with url: models_path, method: :get, class: "mt-3" do |f| %>
      <div class="input-group mb-3">
        <%= f.text_field :q, class: "form-control", placeholder: t(".search.placeholder"), aria_label: "Search", aria_describedby: "button-search", value: @query, autofocus: true %>
        <%= f.submit "Search", class: "btn btn-primary", name: nil %>
      </div>
    <% end %>
  </div>
</div>
<% if @recent %>
  <div class="row row-cols-2">
    <div class="col-8 offset-md-2">
      <p class="lead"><%= t(".recent") %></p>
      <table class="table">
        <% @recent.each do |model| %>
        <tr>
          <td>
            <%= link_to model.name, library_model_path(model.library, model) %>
          </td>
          <td>
            <%= status_badges(model) %>
          </td>
          <td><%= link_to model.library.name, model.library %></td>
          <td><%= t(".how_long_ago", time: time_ago_in_words(model.created_at)) %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
<% end %>