config/routes.rb
Rails.application.routes.draw do
  get "problems/index"
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  ActiveAdmin.routes(self)

  resources :users, only: [] do
    resource :settings, only: [:show, :update]
  end

  root to: "home#index"

  resources :uploads, only: [:index, :create]
  resources :libraries do
    member do
      post "scan"
    end
    collection do
      post "scan", action: :scan_all
    end
    resources :models, except: [:index] do
      member do
        post "merge"
      end
      resources :model_files, except: [:index] do
        collection do
          get "edit", action: "bulk_edit"
          patch "update", action: "bulk_update"
        end
      end
    end
  end
  resources :models, only: [:index] do
    collection do
      get "edit", action: "bulk_edit"
      patch "/update", action: "bulk_update"
    end
  end
  resources :creators
  resources :collections
  resources :problems, only: [:index, :update]
end

app/models/creator.rb
class Creator < ApplicationRecord
  has_many :models, dependent: :nullify
  has_many :links, as: :linkable, dependent: :destroy
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  validates :name, uniqueness: {case_sensitive: false}
  validates :slug, uniqueness: true

  default_scope { order(:name) }

  before_validation :slugify_name, if: :name_changed?

  def self.ransackable_attributes(_auth_object = nil)
    ["caption", "created_at", "id", "name", "notes", "slug", "updated_at"]
  end

  def self.ransackable_associations(_auth_object = nil)
    ["links", "models"]
  end

  private

  def slugify_name
    self.slug = name.parameterize
  end
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  include ModelFilters
  before_action :get_creator, except: [:index, :new, :create]

  def index
    if @filters.empty?
      @creators = Creator.all
      @commontags = @tags = ActsAsTaggableOn::Tag.all
    else
      process_filters_init
      process_filters_tags_fetchall
      process_filters
      process_filters_tags_highlight
      @creators = Creator.where(id: @models.map { |model| model.creator_id })
    end

    # Ordering
    @creators = case session["order"]
    when "recent"
      @creators.order(created_at: :desc)
    else
      @creators.order(name: :asc)
    end

    if current_user.pagination_settings["creators"]
      page = params[:page] || 1
      @creators = @creators.page(page).per(current_user.pagination_settings["per_page"])
    end
    render layout: "card_list_page"
  end

  def show
    redirect_to models_path(creator: params[:id])
  end

  def new
    @creator = Creator.new
    @creator.links.build if @creator.links.empty? # populate empty link
    @title = t("creators.general.new")
  end

  def edit
    @creator.links.build if @creator.links.empty? # populate empty link
  end

  def create
    @creator = Creator.create(creator_params)
    redirect_to creators_path, notice: t(".success")
  end

  def update
    @creator.update(creator_params)
    redirect_to creators_path, notice: t(".success")
  end

  def destroy
    @creator.destroy
    redirect_to creators_path, notice: t(".success")
  end

  private

  def get_creator
    if params[:id] == "0"
      @creator = nil
      @title = t(".unknown")
    else
      @creator = Creator.find(params[:id])
      @title = @creator.name
    end
  end

  def creator_params
    params.require(:creator).permit([
      :name,
      :caption,
      :notes,
      links_attributes: [:id, :url, :_destroy]
    ])
  end
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/views/creators/_creator.html.erb
<div class="col mb-4">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= creator.name %></h5>
      <% if creator.caption %>
        <h6 class="card-subtitle mb-2 text-muted"><%= sanitize creator.caption %></h6>
      <% end %>
      <% if creator.notes %>
        <p class="card-text"><%= sanitize creator.notes %></p>
      <% end %>
      <ul class='links'>
        <% creator.links.each do |link| %>
          <li><%= link_to t("sites.%{site}" % {site: link.site}), link.url %></li>
        <% end %>
      </ul>
      <%= link_to pluralize(creator.models.count, "Model").to_s, models_path(creator: creator.id), {class: "btn btn-primary"} %>
      <%= link_to "Edit", edit_creator_path(creator), {class: "btn btn-outline-secondary"} %>
    </div>
  </div>
</div>

app/views/creators/_form.html.erb
<%= form_with model: @creator do |form| %>
  <%= text_input_row form, :name %>
  <%= render "links_form", form: form %>
  <%= text_input_row form, :caption %>
  <%= rich_text_input_row form, :notes %>
  <div class="row mb-4">
    <div class='col'>
      <%= form.submit t("general.save"), class: "btn btn-primary" %>
    </div>
    <% if @creator.persisted? %>
      <div class='col text-end'>
        <%= link_to t("general.delete"), creator_path(@creator), {method: :delete, class: "btn btn-outline-danger"} %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/creators/edit.html.erb
<h1><%= t "creators.general.edit" %></h1>

<%= render "form" %>

app/views/creators/index.html.erb
<% content_for :page_header do %>
  <%= render "application/content_header" %>
<% end %>

<% content_for :items do %>
  <% if current_user.pagination_settings["creators"] %>
    <%= paginate @creators %>
  <% end %>
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 mb-4">
    <%= render @creators %>
  </div>
  <% if current_user.pagination_settings["creators"] %>
    <%= paginate @creators %>
  <% end %>
<% end %>

<% content_for :sidebar do %>
  <%= card :secondary, t(".actions_heading") do %>
    <%= link_to t(".view_unassigned"), models_path(creator: ""), class: "btn btn-outline-secondary mb-3 me-3" %>
    <%= link_to t("creators.general.new"), new_creator_path, class: "btn btn-primary mb-3 me-3" %>
  <% end %>
  <%= render "filters_card" %>
  <% unless @tags.empty? %>
    <%= card :secondary, ActsAsTaggableOn::Tag.model_name.human.pluralize, collapse: "md" do %>
      <%= render "tag_list", tags: @tags - (@tag || []), muted_tags: @tags - @commontags %>
    <% end %>
  <% end %>
<% end %>

app/views/creators/new.html.erb
<h1><%= t("creators.general.new") %></h1>

<%= render "form" %>